const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const browser = await chromium.launch({ channel: 'msedge', headless: true, args: ['--enable-webgl', '--use-gl=angle', '--use-angle=swiftshader'] });
const origin = process.env.VOXEL_URL || 'http://127.0.0.1:5173/';
const screenshot = name => join(tmpdir(), `voxel-${name}.png`);
const errors = [];
const check = (value, message) => { if (!value) throw new Error(message); };
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
await page.goto(origin);
await page.waitForTimeout(1700);
await page.screenshot({ path: screenshot('desktop') });
await page.locator('#continue').click();
await page.waitForTimeout(1200);
await page.screenshot({ path: screenshot('playing') });
const pixels = await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => {
  const gl = document.querySelector('#game').getContext('webgl2');
  resolve([[.2, .3], [.5, .5], [.8, .7]].map(([x, y]) => {
    const color = new Uint8Array(4);
    gl.readPixels(Math.floor(gl.drawingBufferWidth * x), Math.floor(gl.drawingBufferHeight * y), 1, 1, gl.RGBA, gl.UNSIGNED_BYTE, color);
    return [...color];
  }));
})));
const initial = await page.evaluate(() => window.__voxel.player.position.toArray());
await page.keyboard.down('KeyW');
await page.waitForTimeout(400);
await page.keyboard.up('KeyW');
const moved = await page.evaluate(() => window.__voxel.player.position.toArray());
await page.waitForFunction(() => window.__voxel.player.grounded, null, { timeout: 6000 });
const beforeJump = await page.evaluate(() => window.__voxel.player.position.y);
await page.keyboard.down('Space');
await page.waitForTimeout(120);
await page.keyboard.up('Space');
const jumped = await page.evaluate(() => window.__voxel.player.position.y);
await page.waitForTimeout(1200);
await page.keyboard.press('Digit3');
const selection = await page.evaluate(() => window.__voxel.selected);
const edit = await page.evaluate(() => {
  const v = window.__voxel;
  v.player.pitch = -1.4;
  v.player.syncCamera();
  const hit = v.trace();
  if (!hit) return { error: 'no hit' };
  const before = v.world.get(...hit.block);
  v.interact(false);
  const broken = v.world.get(...hit.block);
  const next = v.trace();
  if (!next) return { before, broken, error: 'no placement target' };
  const cell = next.block.map((n, i) => n + next.normal[i]);
  const empty = v.world.get(...cell);
  v.interact(true);
  return { before, broken, cell, empty, placed: v.world.get(...cell), stored: JSON.parse(localStorage.getItem('block-wander-save-v1')).edits[cell.join(',')] };
});
await page.keyboard.press('KeyE');
const inventory = await page.evaluate(() => ({ mode: window.__voxel.mode, count: document.querySelectorAll('.inventory-item').length }));
await page.locator('[data-block="11"]').click();
const equip = await page.locator('.slot.active').getAttribute('aria-label');
await page.reload();
await page.waitForTimeout(1800);
const restored = await page.evaluate(cell => ({ block: window.__voxel.world.get(...cell), slot: document.querySelector('[data-slot="2"]').getAttribute('aria-label') }), edit.cell);
const boundary = await page.evaluate(() => {
  const w = window.__voxel.world;
  w.update(-16.5, 1.5, 2);
  w.buildNext(100);
  const adjacent = () => w.group.children.find(mesh => {
    if (mesh.material.transparent) return false;
    mesh.geometry.computeBoundingBox();
    const box = mesh.geometry.boundingBox;
    return box.min.x >= -16 && box.max.x <= 0 && box.min.z >= 0 && box.max.z <= 16;
  });
  const before = adjacent();
  const changed = w.set(-17, 30, 1, 3);
  return { before: !!before, changed, rebuilt: !!adjacent() && before !== adjacent() };
});
const collision = await page.evaluate(() => {
  const { world, player } = window.__voxel;
  player.position.set(3.5, 32.62, 3.5);
  world.set(4, 31, 3, 3);
  world.set(4, 32, 3, 3);
  player.moveAxis('x', 1);
  const wallX = player.position.x;
  player.position.set(3.5, 33.62, 3.5);
  world.set(3, 30, 3, 3);
  player.moveAxis('y', -3);
  const floorY = player.position.y;
  return { wallX, floorY };
});
const oldSeed = await page.evaluate(() => window.__voxel.world.seed);
await page.locator('#reset').click();
const resetConfirmed = await page.locator('#confirm-reset').isVisible();
await page.locator('#confirm-reset').click();
await page.waitForLoadState('domcontentloaded');
const reset = await page.evaluate(() => ({ seed: window.__voxel.world.seed, edits: Object.keys(window.__voxel.world.edits).length, stored: localStorage.getItem('block-wander-save-v1') }));
await page.close();

const phone = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
phone.on('pageerror', e => errors.push(`mobile: ${e.message}`));
phone.on('console', m => { if (m.type() === 'error') errors.push(`mobile: ${m.text()}`); });
await phone.goto(origin);
await phone.waitForTimeout(1500);
await phone.screenshot({ path: screenshot('mobile') });
await phone.locator('#continue').click();
await phone.waitForTimeout(900);
await phone.screenshot({ path: screenshot('mobile-playing') });
const layout = await phone.evaluate(() => {
  const rect = id => document.querySelector(id).getBoundingClientRect().toJSON();
  return { joystick: rect('#joystick'), actions: rect('.touch-actions'), hotbar: rect('#hotbar'), viewport: [innerWidth, innerHeight], controls: getComputedStyle(document.querySelector('#touch-ui')).display };
});
const stick = await phone.locator('#joystick').boundingBox();
await phone.mouse.move(stick.x + stick.width / 2, stick.y + stick.height / 2);
await phone.mouse.down();
await phone.mouse.move(stick.x + stick.width / 2, stick.y + stick.height / 2 - stick.height * .3, { steps: 4 });
const joystickInput = await phone.evaluate(() => window.__voxel.player.mobileY);
await phone.mouse.up();
const yawBefore = await phone.evaluate(() => window.__voxel.player.yaw);
await phone.mouse.move(300, 270);
await phone.mouse.down();
await phone.mouse.move(340, 285, { steps: 4 });
await phone.mouse.up();
const yawAfter = await phone.evaluate(() => window.__voxel.player.yaw);
const touchEditBefore = await phone.evaluate(() => { const v = window.__voxel; v.player.pitch = -1.25; v.player.syncCamera(); const hit = v.trace(); return hit ? { cell: hit.block, type: hit.type } : null; });
await phone.locator('#touch-break').click();
const touchBroken = await phone.evaluate(cell => cell ? window.__voxel.world.get(...cell) : null, touchEditBefore?.cell);
const touchPlaceBefore = await phone.evaluate(() => { const v = window.__voxel, hit = v.trace(); return hit ? { cell: hit.block.map((n, i) => n + hit.normal[i]), block: v.world.get(...hit.block.map((n, i) => n + hit.normal[i])) } : null; });
await phone.locator('#touch-place').click();
const touchPlaced = await phone.evaluate(cell => cell ? window.__voxel.world.get(...cell) : null, touchPlaceBefore?.cell);
await phone.waitForFunction(() => window.__voxel.player.grounded, null, { timeout: 6000 });
const touchBefore = await phone.evaluate(() => ({ position: window.__voxel.player.position.toArray(), grounded: window.__voxel.player.grounded, jumpHeld: window.__voxel.player.jumpHeld }));
await phone.locator('#touch-jump').dispatchEvent('pointerdown', { pointerId: 42, pointerType: 'touch' });
const touchDown = await phone.evaluate(() => ({ position: window.__voxel.player.position.toArray(), grounded: window.__voxel.player.grounded, jumpHeld: window.__voxel.player.jumpHeld }));
await phone.waitForTimeout(100);
const jumpVelocity = await phone.evaluate(() => window.__voxel.player.velocityY);
const touchAfter = await phone.evaluate(() => ({ position: window.__voxel.player.position.toArray(), grounded: window.__voxel.player.grounded, jumpHeld: window.__voxel.player.jumpHeld }));
await phone.locator('#touch-jump').dispatchEvent('pointerup', { pointerId: 42, pointerType: 'touch' });
await phone.locator('#pause-btn').click();
const pauseMode = await phone.evaluate(() => window.__voxel.mode);
await phone.setViewportSize({ width: 844, height: 390 });
const landscape = await phone.evaluate(() => { const rect = id => document.querySelector(id).getBoundingClientRect().toJSON(); return { modal: rect('#modal'), viewport: [innerWidth, innerHeight] }; });
await phone.locator('#continue').click();
const landscapeControls = await phone.evaluate(() => { const rect = id => document.querySelector(id).getBoundingClientRect().toJSON(); return { joystick: rect('#joystick'), actions: rect('.touch-actions'), hotbar: rect('#hotbar') }; });
await phone.screenshot({ path: screenshot('mobile-landscape') });
console.log(JSON.stringify({ pixels, initial, moved, beforeJump, jumped, selection, edit, inventory, equip, restored, boundary, collision, resetConfirmed, reset, layout, joystickInput, yawBefore, yawAfter, touchEditBefore, touchBroken, touchPlaceBefore, touchPlaced, touchBefore, touchDown, touchAfter, jumpVelocity, pauseMode, landscape, landscapeControls, errors }, null, 2));
try {
  check(new Set(pixels.map(p => p.join(','))).size > 1 && pixels.every(p => p[3] === 255), 'Canvas rendering');
  check(Math.hypot(moved[0] - initial[0], moved[2] - initial[2]) > .15 && jumped > beforeJump + .15, 'Movement or jumping');
  check(selection === 2 && edit.before > 0 && edit.broken === 0 && edit.empty === 0 && edit.placed === 3 && edit.stored === 3, 'Block interactions or save');
  check(inventory.mode === 'inventory' && inventory.count >= 10 && equip.includes('花砖'), 'Inventory');
  check(restored.block === 3 && restored.slot.includes('花砖'), 'Save restoration');
  check(boundary.before && boundary.changed && boundary.rebuilt, 'Adjacent chunk rebuild');
  check(collision.wallX < 3.73 && collision.floorY >= 32.619, 'Player collision');
  check(resetConfirmed && reset.seed !== oldSeed && reset.edits === 0 && reset.stored === null, 'Confirmed world reset');
  check(layout.controls === 'block' && layout.joystick.bottom < layout.hotbar.top && layout.actions.bottom < layout.hotbar.top && layout.hotbar.right <= layout.viewport[0], 'Phone layout');
  check(joystickInput < -.5 && Math.abs(yawAfter - yawBefore) > .05, 'Touch joystick or look');
  check(touchEditBefore?.type > 0 && touchBroken === 0 && touchPlaceBefore?.block === 0 && touchPlaced > 0, 'Touch block actions');
  check(landscape.modal.right <= landscape.viewport[0] && landscapeControls.joystick.bottom < landscapeControls.hotbar.top && landscapeControls.actions.bottom < landscapeControls.hotbar.top, 'Landscape layout');
  check(jumpVelocity > 0 && pauseMode === 'pause' && errors.length === 0, 'Touch controls or browser errors');
} finally { await browser.close(); }
console.log('PASS: desktop and mobile smoke tests');
